Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/10/2025
Var num : real


Inicio

escreva("Escreva um número: ")
leia(num)

se (num mod 2 = 0) então
escreva ("O número é par")
senão

escreva ("O número é ímpar")

fimse


Fimalgoritmo